### PR TITLE
tools: Add reset-to-pull-request script.

### PR DESCRIPTION
**Pull request by derAnfaenger**
I've had this script from the main repo in the `python_zulip_api` repo for quite a while now and it proved useful, so I thought we should check it in.

### CODE REVIEW

**Comment by timabbott** [comment]
It seems reasonable to bring the whole suite of those tools.

**Comment by derAnfaenger** [comment]
Copied over all other git utility scripts I found that had no dependencies.

I excluded `pre-commit`, `commit-msg` and `setup-git-repo`, since those were dependent on vagrant. A slight altercation of e.g. `pre-commit` could make it handy to pre-run our linter, though.

**Comment by derAnfaenger** [comment]
Update: Travis is fixed now. Updated the shebang in `tools/review` from `#!/usr/bin/env python3` to `#!/usr/bin/env python` . I guess this should be fine, since it's only a utility script (on top of that, the `python3` shebang fails on Windows).

**Comment by timabbott** [comment]
Merged, thanks @derAnfaenger!

**Pull request closed without merging**
