### PR TITLE
bridge_with_irc: Check if bot is subscribed to stream at startup.

### LINKED ISSUE #500: bridge_with_irc: Check if the bot is subscribed to the relevant stream on startup.
This way, the important precaution to make sure that the bot is subscribed is no longer necessary, since the bot will print out the problem itself.

### PR DESCRIPTION
**Pull request by rht**
This fixes #500.
- [x] Test this

### CODE REVIEW

**Comment by orientor** [comment]
Workiing properly. Tested.
Screenshot from 2020-03-01 13-31-15

**Comment by rht** [comment]
@orientor appreciate the test!

**Comment by showell** [comment]
@rht Thanks for doing this!  I am sure this will save some troubleshooting headaches.

If either you or @orientor has time, we could probably make this a bit more friendly by reporting all the missing streams by name, and maybe just exit with a non-zero return code rather than having the traceback.

Merging.

**Comment by rht** [comment]
I will let @orientor do the reporting of the stream and the `exit(1)`.

**Pull request merged**
