### PR TITLE
zulip: Give quicker feedback when credentials are wrong

### LINKED ISSUE #533: api: Give quicker feedback if your credentials are wrong
When you use the api and instantiate a Client, it will succeed as long as the credentials are well-formed, even if the credentials aren't actually valid.  Of course, as soon as you try to use them, you'll get a proper error, but it might make sense to have some kind of "ping" method that you can call that literally just makes sure you can connect to the server, so that program can handle that error immediately before starting real work.

More discussion here:

https://chat.zulip.org/#narrow/stream/127-integrations/topic/python.20client/near/813065

Even though this might be a quick fix in terms of the amount of code, I recommend that you work on this only after you've worked with the API a bit and have a feel for the use cases.  A big part of this issue is figuring out the strategy that makes the most sense here.

We'll also want to improve the docs here to reflect any new methods we add or best practices we decide to recommend.

### PR DESCRIPTION
**Pull request by QEDK**
Fixes #533

### CODE REVIEW

**Comment by QEDK** [comment]
@zulipbot add "area: integrations"

**Comment by QEDK** [comment]
@zulipbot add "needs review"

**Comment by QEDK** [comment]
@showell @neiljp I'm not sure if I'm not using zulipbot right but I cannot add labels to mark this for review so I'm pinging both of you as both of you reviewed code in the other related pull request.

**Comment by andersk** [comment]
This causes many errors to be logged and then ignored (with `sys.exit()`, `return 0`, or falling off the end of an `except` block), and it doesn’t change the `Client` constructor at all. I’m pretty sure this is not what the author of #533 had in mind.

**Comment by QEDK** [comment]
> This causes many errors to be logged and then ignored (with `sys.exit()`, `return 0`, or falling off the end of an `except` block), and it doesn’t change the `Client` constructor at all. I’m pretty sure this is not what the author of #533 had in mind.

This is modeled after #592 which is mostly what they wanted in #533 (per comments on that pull). I fixed the structuring, typos and rebasing.

**Comment by andersk** [comment]
#592 has the same problems. One of them was already [mentioned there](https://github.com/zulip/python-zulip-api/pull/592#issuecomment-619693314), and I’ve commented there about the other.

**Comment by QEDK** [comment]
> #592 has the same problems. One of them was already [mentioned there](https://github.com/zulip/python-zulip-api/pull/592#issuecomment-619693314), and I’ve commented there about the other.

I'll open a new PR to address it in the other way.

**Pull request closed without merging**
