### PR TITLE
zephyr_mirror_backend.py: Remove duplicate import.

### PR DESCRIPTION
**Pull request by XavierCooney**
I wrote a script to find duplicate imports, and this was the only one it could find.

### CODE REVIEW

**Comment by showell** [comment]
merged thanks @XavierCooney!

**Comment by neiljp** [comment]
I was intending to glance at this sooner; while it's already been merged, could you clarify why this is a duplicate? I only see one import.

**Comment by XavierCooney** [comment]
@neiljp There were two: 
duplicate_import

**Comment by neiljp** [comment]
Right, apologies.

**Pull request merged**
