### PR TITLE
bots: Set user-agent for individual bots automatically.

### PR DESCRIPTION
**Pull request by neiljp**
I'm unsure how to test if this provides a resolution for #28, since I don't run a server right now, but it seems like it should.

### CODE REVIEW

**Comment by timabbott** [comment]
The code looks correct.  I would probably test manually by just hacking the Zulip API bindings code to print out the User-Agent before sending just to make sure it looks right, but eventually this seems like the kind of thing we'd check in a unit test suite for the framework, which would probably be worth starting to build soon :)

**Comment by neiljp** [comment]
Various locations indicate this looks ok for wikipedia, giving a final user-agent string of (here): `ZulipWikipediaBot (debian; 9.1)`

**Comment by timabbott** [comment]
Great, merging!

**Comment by timabbott** [comment]
Merged, thanks @neiljp!

**Pull request closed without merging**
