### PR TITLE
AI Bot : Create AI Bot.

### PR DESCRIPTION
**Pull request by DhruvThakker**
Customizable AIML based AI Bot

### CODE REVIEW

**Comment by DhruvThakker** [comment]
@showell Please review the code, I have kept all the AIML files to allow the bot to perform better. 
The tests are not getting passed due to some error unrelated to above commit. Please look into it.
Suggest if any changes are to be made.

**Comment by rht** [comment]
@DhruvThakker the assets files shouldn't be committed to the repo. You should add a command to download them at initial setup.

**Comment by PIG208** [comment]
It appears that the contributor isn't active anymore. We might want to close this PR.

**Comment by showell** [comment]
Closing

**Pull request closed without merging**
