### PR TITLE
Added codery bot for competitive programming

### PR DESCRIPTION
**Pull request by Soumi7**

### CODE REVIEW

**Comment by showell** [comment]
Closing this.

**Comment by Soumi7** [comment]
Why?

**Comment by Soumi7** [comment]
All checks have worked.

**Comment by showell** [comment]
@Soumi7 If you're interested in submitting a PR, please start by organizing your commits.  We're not really looking to merge more bots at this time, because we already have lots of useful example bots, and they can be difficult to maintain.  You're welcome to create your own repository for bots that you have created, and you're also welcome to discuss them on https://chat.zulip.org/#narrow/stream/127-integrations

**Pull request closed without merging**
