### PR TITLE
tools/deploy: Annotate tools/deploy using mypy

### PR DESCRIPTION
**Pull request by Shivamgera**
Issue [#338](https://github.com/zulip/python-zulip-api/issues/338).
@aero31aero, please review this.

### CODE REVIEW

**Comment by neiljp** [comment]
@Shivamgera Check Travis - your (type) comments aren't passing the linter, as it stands. You can run run `lint` locally before pushing, in addition to `run-mypy`.

**Comment by Shivamgera** [comment]
@neiljp, Travis checks are failing again, can you please tell me what caused it?

**Comment by aero31aero** [comment]
@showell LGTM for merging. Tested locally. The travis flakes are the same as other PRs of late so can be ignored.

**Comment by showell** [comment]
merged, thanks @Shivamgera @aero31aero @neiljp

**Pull request merged**
