### PR TITLE
Update test_game_handler_bot.py

### PR DESCRIPTION
**Pull request by vinitwadgaonkar**
tried changing !avatar syntax to html tag

### CODE REVIEW

**Comment by vinitwadgaonkar** [comment]
this is for #632

**Comment by vinitwadgaonkar** [comment]
zulipbot

**Comment by vinitwadgaonkar** [comment]
@timabbott please review

**Comment by timabbott** [comment]
Closing, for the same reason as in #641.  Next time, I'd recommend doing two commits in a single PR making the changes in multiple files.

**Pull request closed without merging**
