### PR TITLE
bots: Create Jira Bot.

### PR DESCRIPTION
**Pull request by skunkmb**
*Jira Bot* can interact with the Jira API. It can **display**, **create**, or **edit** an issue. Before use, `username`, `password`, and `domain` must be set in `jira.conf`.

---

### get

You could say,

 > @**Jira Bot** get "BOTS-13"

and it would respond

 > **Issue *BOTS-13*: Some Issue**
 >
 > - Type: *Task*
 > - Description:
 > > Some description.
 > - Creator: *admin*
 > - Project: *Bots*
 > - Priority: *Medium*
 > - Status: *To Do*

### create

You could say

 > @**Jira Bot** create issue "Some issue" in project "BOTS"' with type "Task" with description "This is a description" assigned to "skunkmb" with priority "Medium" labeled "issues, testing" due "2017-01-23"

and an issue would be created:

 > Issue *BOTS-16* is up! https://example.atlassian.net/browse/BOTS-16

### edit

You could say

 > @**Jira Bot** edit issue "BOTS-16" to use description "This is a new description"

and it would edit the description:

 > Issue *BOTS-16* was edited! https://example.atlassian.net/browse/BOTS-16

---

(Done for the *"Create your own jira bot."* Google Code-in task.)

### CODE REVIEW

**Comment by alenavolk** [comment]
LGTM. I'm approving the related task to let Marco start working on something else.

**Comment by skunkmb** [comment]
@alenavolk Thank you!

**Comment by showell** [comment]
@skunkmb Can you squash all these commits into one commit that says "Create jira bot" in the title?  Also, if there are any follow up tasks that might make the bot better, feel free to open an issue for it if you don't have time right away to do them.

**Comment by skunkmb** [comment]
@showell OK, squashed. Thanks!

**Comment by showell** [comment]
Merged!  thanks @skunkmb @alenavolk

**Pull request merged**
