### PR TITLE
zulip/zulip/__init__.py: Update `reaction_data` type.

### PR DESCRIPTION
**Pull request by LoopThrough-i-j**
Update `reaction_data` type in add_reaction and
remove_reaction, from Dict[str, str] to Dict[str, Any]

### CODE REVIEW

**Comment by amanagr** [comment]
For both the PRs, you don't need to write the whole file name in the commit message.  See https://zulip.readthedocs.io/en/latest/contributing/version-control.html#commit-messages

Something like `reactions_api` would be more appropriate.

**Comment by LoopThrough-i-j** [comment]
Actually, I saw Anders Kaseorg doing this for single file changes, hence thought that could be a better practice for a single file commit.

**Comment by rht** [comment]
Posting the relevant discussion thread for future reference: https://chat.zulip.org/#narrow/stream/127-integrations/topic/msg.20id.20in.20add_emoji.20doc.

**Comment by timabbott** [comment]
Merged, thanks @LoopThrough-i-j!

**Pull request merged**
