### PR TITLE
Add twitpost bot.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
This bot makes it possible to tweet on twitter from Zulip chat itself.
Discussion:
https://chat.zulip.org/#narrow/stream/127-integrations/topic/adding.20a.20bot
https://chat.zulip.org/#narrow/stream/127-integrations/topic/hackathon.20bots

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
@roberthoenig please review

**Comment by Anupam-dagar** [comment]
@roberthoenig @showell please review :smile:

**Comment by showell** [comment]
This LGTM once the commit message gets cleaned up, and we should add a quick readme for setting up the config, which can be part of the first commit.

**Comment by Anupam-dagar** [comment]
@showell this is ready for a review :smile:

**Comment by showell** [comment]
Merged, thanks @Anupam-dagar!

**Pull request merged**
