### PR TITLE
[WIP] bots: Improve input handling

### LINKED ISSUE #6: bots: Encode URLs properly to outbound sites.
See https://github.com/zulip/zulip/issues/5152.

### PR DESCRIPTION
**Pull request by neiljp**
This is intended to resolve #6, but also a few other case(s) that may exists with input handling.

So far:
* Wikipedia: URL handling
* Define: initially just avoiding symbols, but this is complex in python3; the API is unclear, but it likely only accepts ascii, so that's the limit I've put in now.

### CODE REVIEW

**Comment by rht** [comment]
LGTm for the wikipedia and define bot commits.

**Comment by timabbott** [comment]
@neiljp thanks for working on this!  The commits you've done so far look great.  Are they ready to merge from your perspective?  If so, I'd be happy to merge them (I generally don't merge anything on a WIP without a clear indication from the author that they think those pieces are ready).

**Comment by rht** [comment]
The WIP is to signify that other bot files *in general* are going to be patched in the same method, I think. So the current commits are safe to merge.

**Comment by timabbott** [comment]
OK, merged what you have so far, thanks @neiljp!

**Pull request closed without merging**
