### PR TITLE
test_tictactoe.py improvements

### PR DESCRIPTION
**Pull request by kishanlp**
Slightly increased coverage for tictactoe.py from 19% to 20%. Will need further review to test the integration of different functions within the tictactoe bot, as many of the functions seem to not be able to be tested due to bad function calls within the bot code. Additionally, we found that the current tests for the TicTacToeModel object could not be run without explicitly defining current_board outside of the constructor, so we fixed this in order to run our test cases.

### CODE REVIEW

**Comment by showell** [comment]
Hi @kishanlp are you still planning to finish this up?  If not, that's not a problem, we can have somebody else try to clean up the commits a bit.

**Comment by showell** [comment]
@novokrest Do you have any interest in taking over this PR?  The test code looks pretty reasonable, and it's possible that you can mostly squash the commits together into one big commit.  (For adding tests, we don't need to be super granular.)  There's one change to the actual code that I'm not sure is necessary.

**Comment by novokrest** [comment]
@showell I prepared PR based on current: #443

**Comment by showell** [comment]
Closing this.  @kishanlp Thanks for the work on this--we merged it via #443.  @novokrest Thanks for taking it to the finish line.

**Pull request closed without merging**
